#!/bin/bash

# make bash behave
set -euo pipefail
IFS=$'\n\t'

pgversions='9.4 9.5'
topdir=$(pwd)
dockerfiles_dir="${topdir}/dockerfiles"

badusage=64

while read -r line; do
    IFS=',' read -r os release <<< "$line"

    if [[ "${os}" = 'debian' ]] || [[ "${os}" = 'ubuntu' ]]; then
        tag="${os}-${release}-all"
        docker build -t "citusdata/packaging:${tag}" \
                     -f "${dockerfiles_dir}/${tag}/Dockerfile" .
    elif [[ "${os}" = 'centos' ]] || [[ "${os}" = 'fedora' ]] || [[ "${os}" = 'oraclelinux' ]]; then
        # redhat variants need an image for each PostgreSQL version
        IFS=' '
        for pgversion in ${pgversions}; do
            pgshort=${pgversion//./}
            tag="${os}-${release}-pg${pgshort}"
            docker build -t "citusdata/packaging:${tag}" \
                         -f "${dockerfiles_dir}/${tag}/Dockerfile" .
        done
    elif [[ "${os}" = 'pgxn' ]]; then
        tag="${os}-all"
        docker build -t "citusdata/packaging:${tag}" \
                     -f "${dockerfiles_dir}/${tag}/Dockerfile" .
    else
        echo "$0: unrecognized OS -- ${os}" >&2
        exit $badusage
    fi
done <"${topdir}/os-list.csv"
