#!/bin/sh

set -eu

pg_version=
installation_message="
+--------------------------------------------------------------+
Please run 'sudo citus-enterprise-pg-$pg_version-setup'
to complete the setup of Citus Enterprise
+--------------------------------------------------------------+
"
echo "$installation_message"

