# vim:set ft=dockerfile:
FROM citusdata/buildbox-%%os%%-base:%%release%%

ENV PGVERSION=%%pgversion%%

RUN yum install -y https://%%rpm_url%% \
    && yum install -y postgresql%%pgshort%%-devel \
    && yum clean all

RUN curl -sL https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 \
         -o /usr/bin/jq \
    && chmod +x /usr/bin/jq

RUN curl -s https://packagecloud.io/install/repositories/citusdata/community/script.rpm.sh | bash \
    && yum install -y citus_%%pgshort%% \
    && yum clean all

ENV PATH /scripts:$PATH
COPY scripts /scripts

ENTRYPOINT ["/scripts/fetch_and_build_rpm"]
