# vim:set ft=dockerfile:
FROM %%os%%:%%release%%

RUN apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8 \
    && echo 'deb http://apt.postgresql.org/pub/repos/apt/ %%release%%-pgdg main' > /etc/apt/sources.list.d/pgdg.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        autotools-dev \
        build-essential \
        ca-certificates \
        debhelper \
        devscripts \
        fakeroot \
        flex \
        libedit-dev \
        libfile-fcntllock-perl \
        libpam0g-dev \
        libselinux1-dev \
        libxslt-dev \
        lintian \
        postgresql-server-dev-all \
        wget \
    && rm -rf /var/lib/apt/lists/*

ENV PATH /scripts:$PATH
COPY scripts /scripts
VOLUME /packages

CMD ["/scripts/build_deb_nightly"]
