#!/bin/bash

# make bash behave
set -uo pipefail
IFS=$'\n\t'

# constants
success=0
failure=1

if [ -z ${PACKAGING_PASSPHRASE+x} ]; then
    echo "$0: passphrase not set" >&2
    exit $failure
elif [ -z ${PACKAGING_SECRET_KEY+x} ]; then
    echo "$0: secret key not set" >&2
    exit $failure
fi

gpg --batch --no-tty --trust-model always \
    --import <(echo ${PACKAGING_SECRET_KEY} | base64 -d)

for deb in "$@"
do
    sign_deb "${deb}"
done
